services:
  tarantool:
    container_name: mytarantool
    image: tarantool/tarantool:1.7
    command: tarantool /usr/local/share/tarantool/app.init.lua
    ports:
      - 3301:3301
    volumes:
      - ./app.init.lua:/usr/local/share/tarantool/app.init.lua
  web:
    build: .
    depends_on:
      - tarantool
    command: sh -c './wait-for host:3301 -- cmd'
    ports:
      - "5000:5000"